<a href="https://colab.research.google.com/github/wangyi-123456/114-2-/blob/main/%E3%80%8CHW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1jR3qRQr2ZvWYKNuv8wen_-eTZWdc5a-LLvH7iymn2zw/edit?usp=sharing

In [1]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [2]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/15ozIzdxn0_OBR6HS3WIu7znDsNH2E10lPTzG04vpl-c/edit?usp=sharing')

In [3]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

Empty DataFrame
Columns: []
Index: []

In [9]:
import datetime

In [8]:
# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

sort_str = input("請輸入分類: ")
item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))
payer = input("請輸入付款人: ")
location = input("請輸入地點: ")
pay_method = input("請輸入支付方式: ")
note = input("請輸入備註: ")

請輸入日期 (格式：YYYY-MM-DD): 2026-03-11
請輸入時間 (格式：HH:MM): 11:1
請輸入分類: 飲食
請輸入品項: 鹹水雞
請輸入金額: 140
請輸入付款人: 王羿
請輸入地點: 師大夜市
請輸入支付方式: 現金
請輸入備註: 無

In [10]:
date_str

'2026-03-11'

In [11]:
time_str

'11:1'

In [12]:
item

'鹹水雞'

In [13]:
sort_str

'飲食'

In [14]:
amount

140.0

In [15]:
payer

'王羿'

In [16]:
location

'師大夜市'

In [17]:
pay_method

'現金'

In [18]:
note

'無'

In [23]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '品項': item,
    '金額': amount,
    '分類': sort_str,
    '付款人': payer,
    '地點': location,
    '支付方式': pay_method,
    '備註': note
}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

In [24]:
df

           日期    時間   品項     金額  分類 付款人    地點 支付方式 備註
0  2026-03-11  11:1  鹹水雞  140.0  飲食  王羿  師大夜市   現金  無
1  2026-03-11  11:1  鹹水雞  140.0  飲食  王羿  師大夜市   現金  無
2  2026-03-11  11:1  鹹水雞  140.0  飲食  王羿  師大夜市   現金  無
3  2026-03-11  11:1  鹹水雞  140.0  飲食  王羿  師大夜市   現金  無

In [25]:
# 將 DataFrame 轉換成列表的列表 (list of lists)，這是 gspread 支援的資料格式
data_to_write = df.values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('工作表1')

# 第二步：將資料寫入工作表
worksheet.append_rows(values=data_to_write, value_input_option='USER_ENTERED')
print("資料已成功寫入 Google 工作表！")

資料已成功寫入 Google 工作表！